apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: cicd-finalproject-pvc
spec: 
  storageClassName: skills-network-learner
  resources:
    request:
      storage: 1Gi
    volumeMode: FileSystem
    accessMode: 
    - ReadWriteOnce